"""Rooms logic updated

Revision ID: 27bbdd977ca9
Revises: ec65865f1e2a
Create Date: 2026-03-21 19:29:13.411895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27bbdd977ca9'
down_revision: Union[str, None] = 'ec65865f1e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint(op.f('rooms_level_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'level_id')
    op.drop_column('rooms', 'description')

    op.drop_table('levels')

    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.add_column('rooms', sa.Column('level_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rooms_level_id_fkey'), 'rooms', 'levels', ['level_id'], ['id'])
    op.create_table('levels',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('levels_pkey')),
    sa.UniqueConstraint('name', name=op.f('levels_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
