"""Unique name fix

Revision ID: ec65865f1e2a
Revises: bfd6c5d07873
Create Date: 2026-03-17 00:42:59.271165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec65865f1e2a'
down_revision: Union[str, None] = 'bfd6c5d07873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
